server:
  port: 8090

logging:
  level:
    root: warn
    self.hsb: info
  file:
    name: log/blog-pro.log

image.path: /export/data/images/
file.url: http://www.bshz.xyz:8090/hsblog/images/upload/
